FLASK_APP=main.py
FLASK_DEBUG=1

DB_HOST=localhost
DB_DATABASE=latihan
DB_USERNAME=root
DB_PASSWORD=

JWT_SECRET=INISECRET

MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=armancamp2006@gmail.com
MAIL_PASSWORD=ZaqEdc20