"""berkas todo

Revision ID: 1d4827551808
Revises: 63825d99868c
Create Date: 2020-09-14 11:35:30.308868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4827551808'
down_revision = '63825d99868c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('todo_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_files_created_at'), 'todo_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_todo_files_updated_at'), 'todo_files', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_files_updated_at'), table_name='todo_files')
    op.drop_index(op.f('ix_todo_files_created_at'), table_name='todo_files')
    op.drop_table('todo_files')
    # ### end Alembic commands ###
